import {getRandomTarot} from "@/app/utils/RandomUtils";

const images = [
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-02.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-03.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-04.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-05.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-06.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-07.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-08.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-09.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-10.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-11.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-12.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-13.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-14.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-15.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-16.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-17.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-18.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-19.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-20.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-21.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-01.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/major-22.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/wands-11.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/wands-14.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/wands-13.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/wands-14.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/wands-01.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/wands-02.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/wands-03.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/wands-04.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/wands-05.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/wands-06.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/wands-07.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/wands-08.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/wands-09.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/wands-10.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/cups-11.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/cups-12.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/cups-13.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/cups-14.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/cups-01.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/cups-02.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/cups-03.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/cups-04.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/cups-05.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/cups-06.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/cups-07.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/cups-08.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/cups-09.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/cups-10.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/arcana-11.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/arcana-12.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/arcana-13.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/arcana-14.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/arcana-01.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/arcana-02.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/arcana-03.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/arcana-04.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/arcana-05.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/arcana-06.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/arcana-07.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/arcana-08.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/arcana-09.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/arcana-10.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/swords-11.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/swords-12.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/swords-13.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/swords-14.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/swords-01.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/swords-02.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/swords-03.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/swords-04.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/swords-05.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/swords-06.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/swords-07.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/swords-08.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/swords-09.jpg",
    "https://clwater-halo.oss-cn-shanghai.aliyuncs.com/tarot/swords-10.jpg",

]



export function getRandImage() {
    return images[getRandomTarot()]
}